### PR TITLE
accept string as size

### PR DESCRIPTION
**Pull request by ritz078**

### CODE REVIEW

**Comment by arunoda** [comment]
What's the reason for this?
Accept em ?

**Comment by ritz078** [comment]
sending 0 won't work as expected si I had to send `0px`. Didn't wanted to change the core source code, so made a change here.

**Comment by arunoda** [comment]
Okay. sure. I'll take this and do a PR.

**Comment by arunoda** [comment]
@mnmtanish if you are infront of a dev box, do a release.

**Comment by arunoda** [comment]
@ritz078 Check now . `v1.3.0`.

**Pull request merged**
